version: '3.4'

services:
  rediscacheapi:
    image: ${DOCKER_REGISTRY-}rediscacheapi
    build:
      context: .
      dockerfile: RedisCacheApi/Dockerfile

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    ports:
      - "1235:1235"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1235
      - MSSQL_SA_PASSWORD=S3cur3P@ssW0rd!

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "5555:6379" 
    volumes:
      - ./data:/data