// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisCacheApi.Data;

#nullable disable

namespace RedisCacheApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217135532_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedisCacheApi.Models.DbFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FolderForeignId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FolderForeignId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderForeignId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FolderForeignId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFile", b =>
                {
                    b.HasOne("RedisCacheApi.Models.DbFolder", "FolderForeign")
                        .WithMany("Files")
                        .HasForeignKey("FolderForeignId");

                    b.Navigation("FolderForeign");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.HasOne("RedisCacheApi.Models.DbFolder", "FolderForeign")
                        .WithMany("Folders")
                        .HasForeignKey("FolderForeignId");

                    b.Navigation("FolderForeign");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
