// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisCacheApi.Data;

#nullable disable

namespace RedisCacheApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217135816_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedisCacheApi.Models.DbFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FolderForeignId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FolderForeignId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = "File:971f975d-0c7b-4ff7-941a-7c4120100859",
                            Content = "File 1 Content",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 1"
                        },
                        new
                        {
                            Id = "File:9e9861b1-124d-45b4-ba53-501b3e018262",
                            Content = "File 2 Content",
                            FolderForeignId = "Folder:64717275-2d1b-4aa7-91bd-da2c2a097842",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 2"
                        },
                        new
                        {
                            Id = "File:00230b6a-b454-4d0b-9fb9-a5a532264487",
                            Content = "File 3 Content",
                            FolderForeignId = "Folder:64717275-2d1b-4aa7-91bd-da2c2a097842",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 3"
                        },
                        new
                        {
                            Id = "File:dc840741-0cd5-405c-afa5-f2e55817e1a7",
                            Content = "File 4 Content",
                            FolderForeignId = "Folder:b9d00fc5-27c8-4a81-8708-2282f8052912",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 4"
                        },
                        new
                        {
                            Id = "File:7de65e90-7608-470d-a2d7-d0cc56e66e3c",
                            Content = "File 5 Content",
                            FolderForeignId = "Folder:62eae15b-fbef-4f6d-9445-89ba67797ba6",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 5"
                        },
                        new
                        {
                            Id = "File:7b803093-480d-4d2e-8d4d-dbe6e514c4f0",
                            Content = "File 6 Content",
                            FolderForeignId = "Folder:62eae15b-fbef-4f6d-9445-89ba67797ba6",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 6"
                        },
                        new
                        {
                            Id = "File:462cae2c-eef9-4624-aea3-35c304bba233",
                            Content = "File 7 Content",
                            FolderForeignId = "Folder:62eae15b-fbef-4f6d-9445-89ba67797ba6",
                            LastTimeUsed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "File 7"
                        });
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderForeignId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FolderForeignId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = "Folder:64717275-2d1b-4aa7-91bd-da2c2a097842",
                            Name = "Folder 1"
                        },
                        new
                        {
                            Id = "Folder:b9d00fc5-27c8-4a81-8708-2282f8052912",
                            FolderForeignId = "Folder:64717275-2d1b-4aa7-91bd-da2c2a097842",
                            Name = "Folder 2"
                        },
                        new
                        {
                            Id = "Folder:62eae15b-fbef-4f6d-9445-89ba67797ba6",
                            FolderForeignId = "Folder:b9d00fc5-27c8-4a81-8708-2282f8052912",
                            Name = "Folder 3"
                        },
                        new
                        {
                            Id = "Folder:bc52e188-520e-4d2a-b010-99ad0993cf2f",
                            FolderForeignId = "Folder:b9d00fc5-27c8-4a81-8708-2282f8052912",
                            Name = "Folder 4"
                        });
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFile", b =>
                {
                    b.HasOne("RedisCacheApi.Models.DbFolder", "FolderForeign")
                        .WithMany("Files")
                        .HasForeignKey("FolderForeignId");

                    b.Navigation("FolderForeign");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.HasOne("RedisCacheApi.Models.DbFolder", "FolderForeign")
                        .WithMany("Folders")
                        .HasForeignKey("FolderForeignId");

                    b.Navigation("FolderForeign");
                });

            modelBuilder.Entity("RedisCacheApi.Models.DbFolder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
